[package]
name = "macka"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
anyhow = "1"
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = "2.0.114"
toml = "0.8"
wasmparser = "0.239.0"
wit-component = "0.239.0"
wit-parser = "0.239.0"
